name: Test Project
on: [push, workflow_dispatch] # multiple events/triggers
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  deploy:
    needs: test-project # condition to run this job ONLY if above job is successfully completes
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
      - name: Build project
        run: npm rub build
      - name: Deploy
        run: echo "Deploying..."    
